// Germany, from research/germany.md (checked 29 Sep 2026).
// No car toll. What bites is the low-emission zone at the destination, the
// diesel bans inside some of them, and the alpine-symbol winter-tyre rule.

import {claim, type Doc, localized, penalty, ref, refs, S, source} from './helpers'

export const sources: Doc[] = [
  source('de-bfstrmg-1', {
    title: '§ 1 BFStrMG: toll only for goods vehicles over 3.5 t',
    url: 'https://www.gesetze-im-internet.de/bfstrmg/__1.html',
    publisher: 'Bundesministerium der Justiz (gesetze-im-internet.de)',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-curia-c-591-17', {
    title: 'Court of Justice of the EU, C-591/17 Austria v Germany (car toll)',
    url: 'https://curia.europa.eu/juris/liste.jsf?num=C-591/17',
    publisher: 'Court of Justice of the European Union',
    language: 'en',
    trust: 'official',
    country: 'de',
    pageDate: '2019-06-18',
  }),
  source('de-nordkurier-no-toll-2026', {
    title: 'Kommt jetzt eine Maut für Autofahrer? Verkehrsminister spricht ein Machtwort',
    url: 'https://www.nordkurier.de/politik/kommt-jetzt-eine-maut-fuer-autofahrer-verkehrsminister-spricht-ein-machtwort-4658714',
    publisher: 'Nordkurier',
    language: 'de',
    trust: 'press',
    country: 'de',
    pageDate: '2026-06-23',
  }),
  source('de-nordkurier-bilger-2026', {
    title: 'Von der Pkw-Maut lässt Bilger die Finger weg',
    url: 'https://www.nordkurier.de/politik/von-der-pkw-maut-laesst-bilger-die-finger-weg-4798187',
    publisher: 'Nordkurier',
    language: 'de',
    trust: 'press',
    country: 'de',
    pageDate: '2026-08-20',
  }),
  source('de-uba-umweltzonen', {
    title: 'Umweltbundesamt: Umweltzonen in Deutschland (map and list)',
    url: 'https://gis.uba.de/website/umweltzonen/',
    publisher: 'Umweltbundesamt',
    language: 'de',
    trust: 'official',
    country: 'de',
    pageDate: '2026-08-26',
  }),
  source('de-bkatv-annex', {
    title: 'Bußgeldkatalog-Verordnung, Anlage (no. 5a winter tyres, no. 153 Umweltzone)',
    url: 'https://www.gesetze-im-internet.de/bkatv_2013/anlage.html',
    publisher: 'Bundesministerium der Justiz (gesetze-im-internet.de)',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-munich-umweltzone', {
    title: 'Stadt München: Umweltzone München',
    url: 'https://stadt.muenchen.de/infos/umweltzone-muenchen.html',
    publisher: 'Landeshauptstadt München',
    language: 'de',
    trust: 'official',
    country: 'de',
    pageDate: '2026-01-01',
  }),
  source('de-munich-guests', {
    title: 'muenchen.de: Umweltzone und Diesel-Fahrverbot in München',
    url: 'https://www.muenchen.de/verkehr/autos/umweltzone-und-diesel-fahrverbot-muenchen-alle-infos',
    publisher: 'muenchen.de',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-stuttgart-diesel', {
    title: 'Stuttgart: diesel traffic ban',
    url: 'https://www.stuttgart.de/en/leben/mobilitaet/dieselverkehrsverbot/dieselverkehrsverbot',
    publisher: 'Landeshauptstadt Stuttgart',
    language: 'en',
    trust: 'official',
    country: 'de',
    pageDate: '2026-02-24',
  }),
  source('de-berlin-foreign-vehicles', {
    title: 'Berlin: Umweltzone, Fahrzeuge aus dem Ausland',
    url: 'https://www.berlin.de/sen/uvk/umwelt/luft/luftreinhaltung/umweltzone/fahrzeuge-aus-dem-ausland/',
    publisher: 'Senatsverwaltung Berlin',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-berlin-lez-general', {
    title: 'Berlin: Umweltzone, Allgemeines',
    url: 'https://www.berlin.de/sen/uvk/umwelt/luft/luftreinhaltung/umweltzone/allgemeines/',
    publisher: 'Senatsverwaltung Berlin',
    language: 'de',
    trust: 'official',
    country: 'de',
    notes: 'Says the fine is 80 euros; BKatV no. 153 sets 100 euros.',
  }),
  source('de-berlin-tourist-pdf', {
    title: 'Berlin: Umweltzone, information for foreign visitors (PDF)',
    url: 'https://www.berlin.de/sen/uvk/_assets/umwelt/luft/luftreinhaltung/umweltzone/umweltzone_info_ausl_touristen.pdf',
    publisher: 'Senatsverwaltung Berlin',
    language: 'de',
    trust: 'official',
    country: 'de',
    notes: 'Old leaflet still linked: yellow stickers for foreign cars until 2014, 80-euro fine, 40 zones.',
  }),
  source('de-bmuv-umweltplakette', {
    title: 'Bundesumweltministerium: Umweltplakette und Umweltzone',
    url: 'https://www.bundesumweltministerium.de/themen/luft-laerm-mobilitaet/luft/umweltplakette-umweltzone',
    publisher: 'Bundesministerium für Umwelt',
    language: 'de',
    trust: 'official',
    country: 'de',
    pageDate: '2022-07-06',
    notes: 'Green-sticker rules are right; the 80-euro fine is out of date.',
  }),
  source('de-tuev-nord-sticker', {
    title: 'TÜV NORD: buy an environmental badge online',
    url: 'https://www.tuev-nord.de/en/services/driving-licence-and-vehicle/environmental-sticker/buy-an-environmental-badge/',
    publisher: 'TÜV NORD',
    language: 'en',
    trust: 'club',
    country: 'de',
  }),
  source('de-berlin-labo-sticker', {
    title: 'Service Berlin: Feinstaubplakette beantragen',
    url: 'https://service.berlin.de/dienstleistung/121490/',
    publisher: 'Landesamt für Bürger- und Ordnungsangelegenheiten Berlin',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-bimschv-35-annex-3', {
    title: '35. BImSchV Anhang 3: exemptions (motorcycles)',
    url: 'https://www.gesetze-im-internet.de/bimschv_35/anhang_3.html',
    publisher: 'Bundesministerium der Justiz (gesetze-im-internet.de)',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-stvo-2', {
    title: '§ 2 StVO (winter tyres in wintry conditions)',
    url: 'https://www.gesetze-im-internet.de/stvo_2013/__2.html',
    publisher: 'Bundesministerium der Justiz (gesetze-im-internet.de)',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-stvzo-36', {
    title: '§ 36 StVZO (winter tyre = alpine symbol)',
    url: 'https://www.gesetze-im-internet.de/stvzo_2012/__36.html',
    publisher: 'Bundesministerium der Justiz (gesetze-im-internet.de)',
    language: 'de',
    trust: 'official',
    country: 'de',
  }),
  source('de-polizei-bayern-ms', {
    title: 'Polizei Bayern: M+S tyres only until 30 Sep 2024',
    url: 'https://www.polizei.bayern.de/verkehr/verkehrsrecht/005372/index.html',
    publisher: 'Bayerische Polizei',
    language: 'de',
    trust: 'official',
    country: 'de',
    pageDate: '2026-08-26',
  }),
  // Pages drivers still find that say something else.
  source('de-wallstreet-car-toll', {
    title: 'Germania introduce taxa de autostrada pentru toate autoturismele',
    url: 'https://www.wall-street.ro/articol/Auto/205262/acord-intre-germania-si-ce-taxa-de-autostrada-pentru-toate-autoturismele.html',
    publisher: 'Wall-Street.ro',
    language: 'ro',
    trust: 'press',
    country: 'de',
    pageDate: '2016-12-03',
  }),
  source('de-anwalt-munich-euro5', {
    title: 'Dieselfahrverbot in München: Fahrverbot für Euro 4 und Euro 5 Diesel',
    url: 'https://anwalt-verbraucherschutz.de/aktuelles/10-02-2023-dieselfahrverbot-in-muenchen-fahrverbot-fuer-euro-4-und-euro-5-diesel',
    publisher: 'anwalt-verbraucherschutz.de',
    language: 'de',
    trust: 'blog',
    country: 'de',
    pageDate: '2023-02-10',
  }),
]

export const country: Doc = {
  _id: 'country-de',
  _type: 'country',
  code: 'DE',
  name: localized('Germany', {ro: 'Germania', de: 'Deutschland', hu: 'Németország'}),
  currency: 'EUR',
  carTollSummary:
    'No motorway toll or vignette for cars up to 3.5 t. The German car toll was struck down by the EU Court of Justice in 2019, and in August 2026 the new transport minister, Steffen Bilger, said he would not start a new one.',
  sources: refs(S('de-bfstrmg-1'), S('de-curia-c-591-17'), S('de-nordkurier-no-toll-2026'), S('de-nordkurier-bilger-2026')),
}

const free = (id: string, road: string, from: string, to: string, lengthKm: number): Doc => ({
  _id: `section-de-${id}`,
  _type: 'roadSection',
  country: ref('country-de'),
  road,
  from,
  to,
  lengthKm,
  tolled: false,
  note: 'No toll for vehicles up to 3.5 t (BFStrMG § 1).',
  sources: refs(S('de-bfstrmg-1')),
})

export const sections: Doc[] = [
  free('a8-walserberg-munich', 'A 8', 'Walserberg (Austrian border)', 'Munich', 140),
  free('a8-munich-stuttgart', 'A 8', 'Munich', 'Stuttgart', 230),
  free('a3-passau-frankfurt', 'A 3', 'Passau (Austrian border at Suben)', 'Frankfurt am Main', 460),
  free('a3-a9-passau-berlin', 'A 3 / A 93 / A 9', 'Passau (Austrian border at Suben)', 'Berlin', 600),
]

const lezFine = penalty({
  min: 100,
  max: 100,
  currency: 'EUR',
  note: '100 euros, no points (BKatV no. 153); 128.50 euros with fees in Munich and Stuttgart. Some official pages still say 80 euros.',
  source: 'de-bkatv-annex',
})

const HOW_TO_STICKER =
  'Order a green Umweltplakette before you go: TÜV NORD sells it online for 19.90 euros for cars registered abroad (post, pay by invoice); you upload the registration certificate. Berlin’s registration office charges from 5.95 euros but takes 3–4 weeks. Write the plate on the sticker. You do not need it to enter Germany, only to enter a signed zone.'

function lez(id: string, city: string, title: string, area: string, since: string, sources: string[]): Doc {
  return {
    _id: `zone-${id}`,
    _type: 'zone',
    title,
    city: ref(`place-${city}`),
    kind: 'lowEmissionZone',
    status: 'active',
    requiredSticker: 'green',
    area,
    effectiveFrom: since,
    howToComply: HOW_TO_STICKER,
    penalty: lezFine,
    sources: refs(...sources.map(S)),
  }
}

export const zones: Doc[] = [
  lez('munich-lez', 'munich', 'Munich low-emission zone (green sticker)', 'On and inside the Mittlerer Ring, the ring road included since 1 Feb 2023.', '2008-10-01', [
    'de-munich-umweltzone',
    'de-munich-guests',
    'de-uba-umweltzonen',
  ]),
  {
    _id: 'zone-munich-diesel-euro4',
    _type: 'zone',
    title: 'Munich: no diesel Euro 4 or older in the low-emission zone',
    city: ref('place-munich'),
    kind: 'dieselBan',
    status: 'active',
    dieselMinEuro: 5,
    area: 'The whole Munich low-emission zone including the Mittlerer Ring. Residents and delivery traffic are exempt by sign, visitors are not. There is no Euro 5 ban in 2026.',
    effectiveFrom: '2023-02-01',
    howToComply: 'Park outside the Mittlerer Ring and take public transport, or come with a Euro 5 or newer diesel.',
    penalty: lezFine,
    sources: refs(S('de-munich-umweltzone')),
  },
  lez('stuttgart-lez', 'stuttgart', 'Stuttgart low-emission zone (green sticker)', 'The whole city of Stuttgart.', '2008-03-01', ['de-stuttgart-diesel', 'de-uba-umweltzonen']),
  {
    _id: 'zone-stuttgart-diesel-euro4',
    _type: 'zone',
    title: 'Stuttgart: no diesel Euro 4 or older anywhere in the city',
    city: ref('place-stuttgart'),
    kind: 'dieselBan',
    status: 'active',
    dieselMinEuro: 5,
    area: 'The whole city of Stuttgart, all year.',
    effectiveFrom: '2019-01-01',
    howToComply: 'Park outside Stuttgart (Park and Ride) or come with a Euro 5 or newer diesel.',
    penalty: lezFine,
    sources: refs(S('de-stuttgart-diesel')),
  },
  {
    _id: 'zone-stuttgart-diesel-euro5',
    _type: 'zone',
    title: 'Stuttgart: no diesel Euro 5 or older in the “small environmental zone”',
    city: ref('place-stuttgart'),
    kind: 'dieselBan',
    status: 'active',
    dieselMinEuro: 6,
    area: 'The Stuttgart basin and the districts Bad Cannstatt, Feuerbach and Zuffenhausen. Three access routes are exempt. Subject to further court decisions.',
    effectiveFrom: '2020-07-01',
    howToComply: 'With a Euro 5 diesel, stay outside the small zone: park at the edge and take public transport.',
    penalty: lezFine,
    sources: refs(S('de-stuttgart-diesel'), S('de-uba-umweltzonen')),
  },
  lez('berlin-lez', 'berlin', 'Berlin low-emission zone (green sticker)', 'Inside the S-Bahn ring. All street-specific diesel bans were lifted by September 2022.', '2008-01-01', [
    'de-berlin-foreign-vehicles',
    'de-uba-umweltzonen',
  ]),
  lez('frankfurt-lez', 'frankfurt', 'Frankfurt low-emission zone (green sticker)', 'Most of the city inside the motorway ring. No diesel bans beyond the green sticker.', '2008-10-01', [
    'de-uba-umweltzonen',
  ]),
]

export const rules: Doc[] = [
  {
    _id: 'rule-de-winter-tyres',
    _type: 'rule',
    country: ref('country-de'),
    topic: 'winterTyres',
    title: 'Winter tyres with the alpine symbol in wintry conditions (Germany)',
    requirement:
      'On black ice, snow, slush or frost, every wheel needs a winter tyre with the alpine symbol (mountain with snowflake, 3PMSF). Tyres marked only M+S stopped counting on 1 Oct 2024. Applies to foreign cars; motorcycles are exempt.',
    vehicles: ['car', 'carTrailer', 'camper'],
    conditional: true,
    condition: 'Whenever the road is wintry, on any date. There is no calendar period in Germany.',
    effectiveFrom: '2024-10-01',
    severity: 'critical',
    penalty: penalty({
      min: 60,
      max: 80,
      currency: 'EUR',
      points: 1,
      note: '60 euros and 1 point; 80 euros if you hold up traffic.',
      source: 'de-bkatv-annex',
    }),
    sources: refs(S('de-stvo-2'), S('de-stvzo-36'), S('de-polizei-bayern-ms')),
  },
  {
    _id: 'rule-de-border-checks',
    _type: 'rule',
    country: ref('country-de'),
    topic: 'border',
    title: 'Border checks at all German land borders until 15 March 2027',
    requirement: 'Germany checks all its land borders, including the one with Austria. Carry an ID card or passport for everyone in the car.',
    vehicles: ['car', 'carTrailer', 'camper', 'motorcycle'],
    effectiveFrom: '2026-09-16',
    effectiveTo: '2027-03-15',
    severity: 'important',
    sources: refs(S('eu-border-controls')),
  },
  {
    _id: 'rule-de-sticker-motorcycles',
    _type: 'rule',
    country: ref('country-de'),
    topic: 'other',
    title: 'Motorcycles need no environmental sticker (Germany)',
    requirement: 'Two- and three-wheeled motor vehicles are exempt from low-emission zones.',
    vehicles: ['motorcycle'],
    severity: 'info',
    sources: refs(S('de-bimschv-35-annex-3')),
  },
]

export const claims: Doc[] = [
  claim('de-car-toll', {
    statement: 'Germany introduces a motorway toll for all cars.',
    quote: 'Germania introduce taxa de autostrada pentru toate autoturismele',
    seenOn: 'de-wallstreet-car-toll',
    country: 'de',
    verdict: 'outdated',
    correctedBy: ['section-de-a8-walserberg-munich', 'section-de-a3-passau-frankfurt', 'section-de-a8-munich-stuttgart', 'section-de-a3-a9-passau-berlin'],
    explanation:
      'The EU Court of Justice struck the car toll down on 18 Jun 2019 (C-591/17). There is no car toll in 2026, and the new transport minister said in August 2026 that he would not start one.',
  }),
  claim('de-munich-euro5-ban', {
    statement: 'Euro 5 diesels may no longer enter the Munich low-emission zone.',
    quote: 'Auch Dieselfahrzeuge der Schadstoffklasse Euro 5 dürfen nicht mehr',
    seenOn: 'de-anwalt-munich-euro5',
    country: 'de',
    verdict: 'outdated',
    correctedBy: ['zone-munich-diesel-euro4'],
    explanation: 'The Euro 5 stage never came into force. In 2026 Munich only restricts Euro 4 diesels and older; Euro 5 diesels with a green sticker may enter.',
  }),
  claim('de-berlin-fine-80', {
    statement: 'Driving in the Berlin low-emission zone without a green sticker costs 80 euros.',
    quote: 'kostet 80 Euro Bußgeld',
    seenOn: 'de-berlin-lez-general',
    country: 'de',
    verdict: 'outdated',
    correctedBy: ['zone-berlin-lez'],
    explanation: 'An official Berlin page, but the federal fine catalogue (BKatV no. 153) sets 100 euros. The law wins over the page.',
  }),
  claim('de-berlin-pdf-yellow', {
    statement: 'Foreign cars may enter German zones with a yellow sticker; the fine is 80 euros; there are 40 zones.',
    quote: 'noch bis zum 31.12.2014 mit gelber Plakette',
    seenOn: 'de-berlin-tourist-pdf',
    country: 'de',
    verdict: 'outdated',
    correctedBy: ['zone-berlin-lez', 'zone-munich-lez'],
    explanation: 'Green is required for foreign cars too, the fine is 100 euros, and there are 35 active zones (Umweltbundesamt, 26 Aug 2026).',
  }),
  claim('de-bmuv-fine-80', {
    statement: 'The fine for driving in a low-emission zone without a sticker is 80 euros.',
    quote: '(Bußgeld: 80 Euro)',
    seenOn: 'de-bmuv-umweltplakette',
    country: 'de',
    verdict: 'outdated',
    correctedBy: ['zone-munich-lez', 'zone-stuttgart-lez', 'zone-berlin-lez', 'zone-frankfurt-lez'],
    explanation: 'The federal environment ministry page dates from 2022. The fine catalogue (BKatV no. 153) sets 100 euros.',
  }),
]
